name: NUS ISS MTech IS
on: [push, workflow_dispatch]

jobs:
  run-end-to-end-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_md
      - name: Run executable bash script
        run: bash ./run.sh
      